/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fwPaOIJJewt
 */
import { Button } from "@/components/ui/button";

export function SubmitButton({ progress }) {
  if (progress < 100) {
    return null;
  }

  return (
    <Button className="bg-gradient-to-r from-purple-600 to-blue-500 hover:from-pink-500 hover:to-orange-500 transform transition-all duration-500 ease-in-out hover:scale-110 text-white font-bold py-2 px-4 rounded">
      Submit
    </Button>
  );
}
